'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class import_bulk_data

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Header1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header1 As Global.tsma.header1

    '''<summary>
    '''Left1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Left1 As Global.tsma.left1

    '''<summary>
    '''ltrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkLibraryCSVTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLibraryCSVTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkCategoryHelpCSVTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCategoryHelpCSVTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''flProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flProducts As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''chkUpdateExisting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUpdateExisting As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''btnImportFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportFile As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''tblProductError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblProductError As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''grdError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdError As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''tblCustomerError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCustomerError As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''grdErrorCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdErrorCustomer As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ddlAutoPostTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAutoPostTimeZone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer1 As Global.tsma.footer1
End Class
