'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ForrentAuthontication
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://services.customeracceptance.forrent.com/soap/facebookfanpages", ConfigurationName:="ForrentAuthontication.IFacebookPages")>  _
    Public Interface IFacebookPages
        
        'CODEGEN: Generating message contract since the operation GetFacebookPages is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://services.customeracceptance.forrent.com/soap/facebookfanpages", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFacebookPages(ByVal request As ForrentAuthontication.Request1) As ForrentAuthontication.Response1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.customeracceptance.forrent.com/soap/facebookfanpages")>  _
    Partial Public Class SitePageInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private facebookPageUrlField As String
        
        Private forrentSiteIdField As String
        
        Private propertyNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property FacebookPageUrl() As String
            Get
                Return Me.facebookPageUrlField
            End Get
            Set
                Me.facebookPageUrlField = value
                Me.RaisePropertyChanged("FacebookPageUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property ForrentSiteId() As String
            Get
                Return Me.forrentSiteIdField
            End Get
            Set
                Me.forrentSiteIdField = value
                Me.RaisePropertyChanged("ForrentSiteId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property PropertyName() As String
            Get
                Return Me.propertyNameField
            End Get
            Set
                Me.propertyNameField = value
                Me.RaisePropertyChanged("PropertyName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Request1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal token As String)
            MyBase.New
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Response1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public sitepages() As SitePageInfo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sitepages() As SitePageInfo)
            MyBase.New
            Me.sitepages = sitepages
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IFacebookPagesChannel
        Inherits ForrentAuthontication.IFacebookPages, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FacebookPagesClient
        Inherits System.ServiceModel.ClientBase(Of ForrentAuthontication.IFacebookPages)
        Implements ForrentAuthontication.IFacebookPages
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ForrentAuthontication_IFacebookPages_GetFacebookPages(ByVal request As ForrentAuthontication.Request1) As ForrentAuthontication.Response1 Implements ForrentAuthontication.IFacebookPages.GetFacebookPages
            Return MyBase.Channel.GetFacebookPages(request)
        End Function
        
        Public Function GetFacebookPages(ByVal token As String) As SitePageInfo()
            Dim inValue As ForrentAuthontication.Request1 = New ForrentAuthontication.Request1()
            inValue.token = token
            Dim retVal As ForrentAuthontication.Response1 = CType(Me,ForrentAuthontication.IFacebookPages).GetFacebookPages(inValue)
            Return retVal.sitepages
        End Function
    End Class
End Namespace
