'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class crop2

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objScriptMang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objScriptMang As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''uplMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''flImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flImage As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''imgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtCropX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCropX As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCropY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCropY As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCropW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCropW As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCropH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCropH As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImageW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImageW As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImageH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImageH As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCropImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCropImage As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''btnCropResize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCropResize As Global.System.Web.UI.HtmlControls.HtmlInputSubmit

    '''<summary>
    '''hdnX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnY As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnCropX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCropX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnCropY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCropY As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnImageW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageW As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnImageH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageH As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''imgfinalCropImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgfinalCropImage As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lnkDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownload As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
