'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''DivBrowser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivBrowser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''header1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header1 As Global.tsma.headertop

    '''<summary>
    '''pnlLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLocal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlForgotPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForgotPwd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtForget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForget As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPassword As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlmsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlOnline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnline As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''strVideo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strVideo1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''imgWeeklyTips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWeeklyTips As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ltrWeeklyTipsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrWeeklyTipsTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrWeeklyTipsDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrWeeklyTipsDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgFanFriday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFanFriday As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ltrFanFridayTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrFanFridayTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrFanFridayDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrFanFridayDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlsFacebookPlugin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlsFacebookPlugin As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''footer11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents footer11 As Global.tsma.footer

    '''<summary>
    '''hdnAccessToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccessToken As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
