'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class library1

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''src1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents src1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplate As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''rptLibUserCatList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLibUserCatList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtNewLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewLibCat As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lnkCreateNewCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateNewCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hdnLibCatId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLibCatId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnLibCatName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLibCatName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ltrLibMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrLibMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptAdminLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdminLibCat As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptUserLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUserLibCat As Global.System.Web.UI.WebControls.Repeater
End Class
