'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class siteuserlogin

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''header1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header1 As Global.tsma.headertop

    '''<summary>
    '''spnEror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnEror As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtUid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUid As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''txtcode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcode1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgcode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcode1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''hdncode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdncode1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''checker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checker As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''imgLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogin As Global.System.Web.UI.HtmlControls.HtmlInputImage

    '''<summary>
    '''pnlForgotPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForgotPwd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtForget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForget As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPassword As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlmsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''footer11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents footer11 As Global.tsma.footer
End Class
